services:
  fcg-server:
    image: fcg-server:latest
    container_name: fcg-server
    restart: always
    networks:
      - fcg-net
    volumes:
      - /home/user/apps/fcg/config/application-prod.yml:/app/config/application-prod.yml
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/app/config/
      - TZ=Asia/Shanghai

  fcg-web:
    image: fcg-web:latest
    container_name: fcg-web
    restart: always
    ports:
      - "5173:80"
    networks:
      - fcg-net
    depends_on:
      - fcg-server

networks:
  fcg-net:
    driver: bridge
